const HTTP_CODES = {
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND: 404,
  OK: 200,
  FORBIDDEN: 403,
  UNAUTHORIZED: 401,
  BAD_REQUEST: 400
};

const WEATHER_FORECAST_VALIDATION = {
  INVALID_DAY_PARAMETER: `Not allowed format for the DAY parameter`
};

export { HTTP_CODES, WEATHER_FORECAST_VALIDATION };
